# Generated by Django 5.2.3 on 2025-07-27 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='senha',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nome',
            new_name='username',
        ),
    ]
